export const CITIES = [
  { value: '01', label: 'Thành phố Hà Nội' },
  { value: '02', label: 'Tỉnh Hà Giang' },
  { value: '04', label: 'Tỉnh Cao Bằng' },
  { value: '06', label: 'Tỉnh Bắc Kạn' },
  { value: '08', label: 'Tỉnh Tuyên Quang' },
  { value: '10', label: 'Tỉnh Lào Cai' },
  { value: '11', label: 'Tỉnh Điện Biên' },
  { value: '12', label: 'Tỉnh Lai Châu' },
  { value: '14', label: 'Tỉnh Sơn La' },
  { value: '15', label: 'Tỉnh Yên Bái' },
  { value: '17', label: 'Tỉnh Hoà Bình' },
  { value: '19', label: 'Tỉnh Thái Nguyên' },
  { value: '20', label: 'Tỉnh Lạng Sơn' },
  { value: '22', label: 'Tỉnh Quảng Ninh' },
  { value: '24', label: 'Tỉnh Bắc Giang' },
  { value: '25', label: 'Tỉnh Phú Thọ' },
  { value: '26', label: 'Tỉnh Vĩnh Phúc' },
  { value: '27', label: 'Tỉnh Bắc Ninh' },
  { value: '30', label: 'Tỉnh Hải Dương' },
  { value: '31', label: 'Thành phố Hải Phòng' },
  { value: '33', label: 'Tỉnh Hưng Yên' },
  { value: '34', label: 'Tỉnh Thái Bình' },
  { value: '35', label: 'Tỉnh Hà Nam' },
  { value: '36', label: 'Tỉnh Nam Định' },
  { value: '37', label: 'Tỉnh Ninh Bình' },
  { value: '38', label: 'Tỉnh Thanh Hóa' },
  { value: '40', label: 'Tỉnh Nghệ An' },
  { value: '42', label: 'Tỉnh Hà Tĩnh' },
  { value: '44', label: 'Tỉnh Quảng Bình' },
  { value: '45', label: 'Tỉnh Quảng Trị' },
  { value: '46', label: 'Tỉnh Thừa Thiên Huế' },
  { value: '48', label: 'Thành phố Đà Nẵng' },
  { value: '49', label: 'Tỉnh Quảng Nam' },
  { value: '51', label: 'Tỉnh Quảng Ngãi' },
  { value: '52', label: 'Tỉnh Bình Định' },
  { value: '54', label: 'Tỉnh Phú Yên' },
  { value: '56', label: 'Tỉnh Khánh Hòa' },
  { value: '58', label: 'Tỉnh Ninh Thuận' },
  { value: '60', label: 'Tỉnh Bình Thuận' },
  { value: '62', label: 'Tỉnh Kon Tum' },
  { value: '64', label: 'Tỉnh Gia Lai' },
  { value: '66', label: 'Tỉnh Đắk Lắk' },
  { value: '67', label: 'Tỉnh Đắk Nông' },
  { value: '68', label: 'Tỉnh Lâm Đồng' },
  { value: '70', label: 'Tỉnh Bình Phước' },
  { value: '72', label: 'Tỉnh Tây Ninh' },
  { value: '74', label: 'Tỉnh Bình Dương' },
  { value: '75', label: 'Tỉnh Đồng Nai' },
  { value: '77', label: 'Tỉnh Bà Rịa - Vũng Tàu' },
  { value: '79', label: 'Thành phố Hồ Chí Minh' },
  { value: '80', label: 'Tỉnh Long An' },
  { value: '82', label: 'Tỉnh Tiền Giang' },
  { value: '83', label: 'Tỉnh Bến Tre' },
  { value: '84', label: 'Tỉnh Trà Vinh' },
  { value: '86', label: 'Tỉnh Vĩnh Long' },
  { value: '87', label: 'Tỉnh Đồng Tháp' },
  { value: '89', label: 'Tỉnh An Giang' },
  { value: '91', label: 'Tỉnh Kiên Giang' },
  { value: '92', label: 'Thành phố Cần Thơ' },
  { value: '93', label: 'Tỉnh Hậu Giang' },
  { value: '94', label: 'Tỉnh Sóc Trăng' },
  { value: '95', label: 'Tỉnh Bạc Liêu' },
  { value: '96', label: 'Tỉnh Cà Mau' }
]

export const DISTRICTS = [
  { value: '001', label: 'Quận Ba Đình', city: '01' },
  { value: '002', label: 'Quận Hoàn Kiếm', city: '01' },
  { value: '003', label: 'Quận Tây Hồ', city: '01' },
  { value: '004', label: 'Quận Long Biên', city: '01' },
  { value: '005', label: 'Quận Cầu Giấy', city: '01' },
  { value: '006', label: 'Quận Đống Đa', city: '01' },
  { value: '007', label: 'Quận Hai Bà Trưng', city: '01' },
  { value: '008', label: 'Quận Hoàng Mai', city: '01' },
  { value: '009', label: 'Quận Thanh Xuân', city: '01' },
  { value: '016', label: 'Huyện Sóc Sơn', city: '01' },
  { value: '017', label: 'Huyện Đông Anh', city: '01' },
  { value: '018', label: 'Huyện Gia Lâm', city: '01' },
  { value: '019', label: 'Quận Nam Từ Liêm', city: '01' },
  { value: '020', label: 'Huyện Thanh Trì', city: '01' },
  { value: '021', label: 'Quận Bắc Từ Liêm', city: '01' },
  { value: '024', label: 'Thành phố Hà Giang', city: '02' },
  { value: '026', label: 'Huyện Đồng Văn', city: '02' },
  { value: '027', label: 'Huyện Mèo Vạc', city: '02' },
  { value: '028', label: 'Huyện Yên Minh', city: '02' },
  { value: '029', label: 'Huyện Quản Bạ', city: '02' },
  { value: '030', label: 'Huyện Vị Xuyên', city: '02' },
  { value: '031', label: 'Huyện Bắc Mê', city: '02' },
  { value: '032', label: 'Huyện Hoàng Su Phì', city: '02' },
  { value: '033', label: 'Huyện Xín Mần', city: '02' },
  { value: '034', label: 'Huyện Bắc Quang', city: '02' },
  { value: '035', label: 'Huyện Quang Bình', city: '02' },
  { value: '040', label: 'Thành phố Cao Bằng', city: '04' },
  { value: '042', label: 'Huyện Bảo Lâm', city: '04' },
  { value: '043', label: 'Huyện Bảo Lạc', city: '04' },
  { value: '044', label: 'Huyện Thông Nông', city: '04' },
  { value: '045', label: 'Huyện Hà Quảng', city: '04' },
  { value: '046', label: 'Huyện Trà Lĩnh', city: '04' },
  { value: '047', label: 'Huyện Trùng Khánh', city: '04' },
  { value: '048', label: 'Huyện Hạ Lang', city: '04' },
  { value: '049', label: 'Huyện Quảng Uyên', city: '04' },
  { value: '050', label: 'Huyện Phục Hoà', city: '04' },
  { value: '051', label: 'Huyện Hoà An', city: '04' },
  { value: '052', label: 'Huyện Nguyên Bình', city: '04' },
  { value: '053', label: 'Huyện Thạch An', city: '04' },
  { value: '058', label: 'Thành Phố Bắc Kạn', city: '06' },
  { value: '060', label: 'Huyện Pác Nặm', city: '06' },
  { value: '061', label: 'Huyện Ba Bể', city: '06' },
  { value: '062', label: 'Huyện Ngân Sơn', city: '06' },
  { value: '063', label: 'Huyện Bạch Thông', city: '06' },
  { value: '064', label: 'Huyện Chợ Đồn', city: '06' },
  { value: '065', label: 'Huyện Chợ Mới', city: '06' },
  { value: '066', label: 'Huyện Na Rì', city: '06' },
  { value: '070', label: 'Thành phố Tuyên Quang', city: '08' },
  { value: '071', label: 'Huyện Lâm Bình', city: '08' },
  { value: '072', label: 'Huyện Nà Hang', city: '08' },
  { value: '073', label: 'Huyện Chiêm Hóa', city: '08' },
  { value: '074', label: 'Huyện Hàm Yên', city: '08' },
  { value: '075', label: 'Huyện Yên Sơn', city: '08' },
  { value: '076', label: 'Huyện Sơn Dương', city: '08' },
  { value: '080', label: 'Thành phố Lào Cai', city: '10' },
  { value: '082', label: 'Huyện Bát Xát', city: '10' },
  { value: '083', label: 'Huyện Mường Khương', city: '10' },
  { value: '084', label: 'Huyện Si Ma Cai', city: '10' },
  { value: '085', label: 'Huyện Bắc Hà', city: '10' },
  { value: '086', label: 'Huyện Bảo Thắng', city: '10' },
  { value: '087', label: 'Huyện Bảo Yên', city: '10' },
  { value: '088', label: 'Huyện Sa Pa', city: '10' },
  { value: '089', label: 'Huyện Văn Bàn', city: '10' },
  { value: '094', label: 'Thành phố Điện Biên Phủ', city: '11' },
  { value: '095', label: 'Thị Xã Mường Lay', city: '11' },
  { value: '096', label: 'Huyện Mường Nhé', city: '11' },
  { value: '097', label: 'Huyện Mường Chà', city: '11' },
  { value: '098', label: 'Huyện Tủa Chùa', city: '11' },
  { value: '099', label: 'Huyện Tuần Giáo', city: '11' },
  { value: '100', label: 'Huyện Điện Biên', city: '11' },
  { value: '101', label: 'Huyện Điện Biên Đông', city: '11' },
  { value: '102', label: 'Huyện Mường Ảng', city: '11' },
  { value: '103', label: 'Huyện Nậm Pồ', city: '11' },
  { value: '105', label: 'Thành phố Lai Châu', city: '12' },
  { value: '106', label: 'Huyện Tam Đường', city: '12' },
  { value: '107', label: 'Huyện Mường Tè', city: '12' },
  { value: '108', label: 'Huyện Sìn Hồ', city: '12' },
  { value: '109', label: 'Huyện Phong Thổ', city: '12' },
  { value: '110', label: 'Huyện Than Uyên', city: '12' },
  { value: '111', label: 'Huyện Tân Uyên', city: '12' },
  { value: '112', label: 'Huyện Nậm Nhùn', city: '12' },
  { value: '116', label: 'Thành phố Sơn La', city: '14' },
  { value: '118', label: 'Huyện Quỳnh Nhai', city: '14' },
  { value: '119', label: 'Huyện Thuận Châu', city: '14' },
  { value: '120', label: 'Huyện Mường La', city: '14' },
  { value: '121', label: 'Huyện Bắc Yên', city: '14' },
  { value: '122', label: 'Huyện Phù Yên', city: '14' },
  { value: '123', label: 'Huyện Mộc Châu', city: '14' },
  { value: '124', label: 'Huyện Yên Châu', city: '14' },
  { value: '125', label: 'Huyện Mai Sơn', city: '14' },
  { value: '126', label: 'Huyện Sông Mã', city: '14' },
  { value: '127', label: 'Huyện Sốp Cộp', city: '14' },
  { value: '128', label: 'Huyện Vân Hồ', city: '14' },
  { value: '132', label: 'Thành phố Yên Bái', city: '15' },
  { value: '133', label: 'Thị xã Nghĩa Lộ', city: '15' },
  { value: '135', label: 'Huyện Lục Yên', city: '15' },
  { value: '136', label: 'Huyện Văn Yên', city: '15' },
  { value: '137', label: 'Huyện Mù Căng Chải', city: '15' },
  { value: '138', label: 'Huyện Trấn Yên', city: '15' },
  { value: '139', label: 'Huyện Trạm Tấu', city: '15' },
  { value: '140', label: 'Huyện Văn Chấn', city: '15' },
  { value: '141', label: 'Huyện Yên Bình', city: '15' },
  { value: '148', label: 'Thành phố Hòa Bình', city: '17' },
  { value: '150', label: 'Huyện Đà Bắc', city: '17' },
  { value: '151', label: 'Huyện Kỳ Sơn', city: '17' },
  { value: '152', label: 'Huyện Lương Sơn', city: '17' },
  { value: '153', label: 'Huyện Kim Bôi', city: '17' },
  { value: '154', label: 'Huyện Cao Phong', city: '17' },
  { value: '155', label: 'Huyện Tân Lạc', city: '17' },
  { value: '156', label: 'Huyện Mai Châu', city: '17' },
  { value: '157', label: 'Huyện Lạc Sơn', city: '17' },
  { value: '158', label: 'Huyện Yên Thủy', city: '17' },
  { value: '159', label: 'Huyện Lạc Thủy', city: '17' },
  { value: '164', label: 'Thành phố Thái Nguyên', city: '19' },
  { value: '165', label: 'Thành phố Sông Công', city: '19' },
  { value: '167', label: 'Huyện Định Hóa', city: '19' },
  { value: '168', label: 'Huyện Phú Lương', city: '19' },
  { value: '169', label: 'Huyện Đồng Hỷ', city: '19' },
  { value: '170', label: 'Huyện Võ Nhai', city: '19' },
  { value: '171', label: 'Huyện Đại Từ', city: '19' },
  { value: '172', label: 'Thị xã Phổ Yên', city: '19' },
  { value: '173', label: 'Huyện Phú Bình', city: '19' },
  { value: '178', label: 'Thành phố Lạng Sơn', city: '20' },
  { value: '180', label: 'Huyện Tràng Định', city: '20' },
  { value: '181', label: 'Huyện Bình Gia', city: '20' },
  { value: '182', label: 'Huyện Văn Lãng', city: '20' },
  { value: '183', label: 'Huyện Cao Lộc', city: '20' },
  { value: '184', label: 'Huyện Văn Quan', city: '20' },
  { value: '185', label: 'Huyện Bắc Sơn', city: '20' },
  { value: '186', label: 'Huyện Hữu Lũng', city: '20' },
  { value: '187', label: 'Huyện Chi Lăng', city: '20' },
  { value: '188', label: 'Huyện Lộc Bình', city: '20' },
  { value: '189', label: 'Huyện Đình Lập', city: '20' },
  { value: '193', label: 'Thành phố Hạ Long', city: '22' },
  { value: '194', label: 'Thành phố Móng Cái', city: '22' },
  { value: '195', label: 'Thành phố Cẩm Phả', city: '22' },
  { value: '196', label: 'Thành phố Uông Bí', city: '22' },
  { value: '198', label: 'Huyện Bình Liêu', city: '22' },
  { value: '199', label: 'Huyện Tiên Yên', city: '22' },
  { value: '200', label: 'Huyện Đầm Hà', city: '22' },
  { value: '201', label: 'Huyện Hải Hà', city: '22' },
  { value: '202', label: 'Huyện Ba Chẽ', city: '22' },
  { value: '203', label: 'Huyện Vân Đồn', city: '22' },
  { value: '204', label: 'Huyện Hoành Bồ', city: '22' },
  { value: '205', label: 'Thị xã Đông Triều', city: '22' },
  { value: '206', label: 'Thị xã Quảng Yên', city: '22' },
  { value: '207', label: 'Huyện Cô Tô', city: '22' },
  { value: '213', label: 'Thành phố Bắc Giang', city: '24' },
  { value: '215', label: 'Huyện Yên Thế', city: '24' },
  { value: '216', label: 'Huyện Tân Yên', city: '24' },
  { value: '217', label: 'Huyện Lạng Giang', city: '24' },
  { value: '218', label: 'Huyện Lục Nam', city: '24' },
  { value: '219', label: 'Huyện Lục Ngạn', city: '24' },
  { value: '220', label: 'Huyện Sơn Động', city: '24' },
  { value: '221', label: 'Huyện Yên Dũng', city: '24' },
  { value: '222', label: 'Huyện Việt Yên', city: '24' },
  { value: '223', label: 'Huyện Hiệp Hòa', city: '24' },
  { value: '227', label: 'Thành phố Việt Trì', city: '25' },
  { value: '228', label: 'Thị xã Phú Thọ', city: '25' },
  { value: '230', label: 'Huyện Đoan Hùng', city: '25' },
  { value: '231', label: 'Huyện Hạ Hoà', city: '25' },
  { value: '232', label: 'Huyện Thanh Ba', city: '25' },
  { value: '233', label: 'Huyện Phù Ninh', city: '25' },
  { value: '234', label: 'Huyện Yên Lập', city: '25' },
  { value: '235', label: 'Huyện Cẩm Khê', city: '25' },
  { value: '236', label: 'Huyện Tam Nông', city: '25' },
  { value: '237', label: 'Huyện Lâm Thao', city: '25' },
  { value: '238', label: 'Huyện Thanh Sơn', city: '25' },
  { value: '239', label: 'Huyện Thanh Thuỷ', city: '25' },
  { value: '240', label: 'Huyện Tân Sơn', city: '25' },
  { value: '243', label: 'Thành phố Vĩnh Yên', city: '26' },
  { value: '244', label: 'Thị xã Phúc Yên', city: '26' },
  { value: '246', label: 'Huyện Lập Thạch', city: '26' },
  { value: '247', label: 'Huyện Tam Dương', city: '26' },
  { value: '248', label: 'Huyện Tam Đảo', city: '26' },
  { value: '249', label: 'Huyện Bình Xuyên', city: '26' },
  { value: '250', label: 'Huyện Mê Linh', city: '01' },
  { value: '251', label: 'Huyện Yên Lạc', city: '26' },
  { value: '252', label: 'Huyện Vĩnh Tường', city: '26' },
  { value: '253', label: 'Huyện Sông Lô', city: '26' },
  { value: '256', label: 'Thành phố Bắc Ninh', city: '27' },
  { value: '258', label: 'Huyện Yên Phong', city: '27' },
  { value: '259', label: 'Huyện Quế Võ', city: '27' },
  { value: '260', label: 'Huyện Tiên Du', city: '27' },
  { value: '261', label: 'Thị xã Từ Sơn', city: '27' },
  { value: '262', label: 'Huyện Thuận Thành', city: '27' },
  { value: '263', label: 'Huyện Gia Bình', city: '27' },
  { value: '264', label: 'Huyện Lương Tài', city: '27' },
  { value: '268', label: 'Quận Hà Đông', city: '01' },
  { value: '269', label: 'Thị xã Sơn Tây', city: '01' },
  { value: '271', label: 'Huyện Ba Vì', city: '01' },
  { value: '272', label: 'Huyện Phúc Thọ', city: '01' },
  { value: '273', label: 'Huyện Đan Phượng', city: '01' },
  { value: '274', label: 'Huyện Hoài Đức', city: '01' },
  { value: '275', label: 'Huyện Quốc Oai', city: '01' },
  { value: '276', label: 'Huyện Thạch Thất', city: '01' },
  { value: '277', label: 'Huyện Chương Mỹ', city: '01' },
  { value: '278', label: 'Huyện Thanh Oai', city: '01' },
  { value: '279', label: 'Huyện Thường Tín', city: '01' },
  { value: '280', label: 'Huyện Phú Xuyên', city: '01' },
  { value: '281', label: 'Huyện Ứng Hòa', city: '01' },
  { value: '282', label: 'Huyện Mỹ Đức', city: '01' },
  { value: '288', label: 'Thành phố Hải Dương', city: '30' },
  { value: '290', label: 'Thị xã Chí Linh', city: '30' },
  { value: '291', label: 'Huyện Nam Sách', city: '30' },
  { value: '292', label: 'Huyện Kinh Môn', city: '30' },
  { value: '293', label: 'Huyện Kim Thành', city: '30' },
  { value: '294', label: 'Huyện Thanh Hà', city: '30' },
  { value: '295', label: 'Huyện Cẩm Giàng', city: '30' },
  { value: '296', label: 'Huyện Bình Giang', city: '30' },
  { value: '297', label: 'Huyện Gia Lộc', city: '30' },
  { value: '298', label: 'Huyện Tứ Kỳ', city: '30' },
  { value: '299', label: 'Huyện Ninh Giang', city: '30' },
  { value: '300', label: 'Huyện Thanh Miện', city: '30' },
  { value: '303', label: 'Quận Hồng Bàng', city: '31' },
  { value: '304', label: 'Quận Ngô Quyền', city: '31' },
  { value: '305', label: 'Quận Lê Chân', city: '31' },
  { value: '306', label: 'Quận Hải An', city: '31' },
  { value: '307', label: 'Quận Kiến An', city: '31' },
  { value: '308', label: 'Quận Đồ Sơn', city: '31' },
  { value: '309', label: 'Quận Dương Kinh', city: '31' },
  { value: '311', label: 'Huyện Thuỷ Nguyên', city: '31' },
  { value: '312', label: 'Huyện An Dương', city: '31' },
  { value: '313', label: 'Huyện An Lão', city: '31' },
  { value: '314', label: 'Huyện Kiến Thuỵ', city: '31' },
  { value: '315', label: 'Huyện Tiên Lãng', city: '31' },
  { value: '316', label: 'Huyện Vĩnh Bảo', city: '31' },
  { value: '317', label: 'Huyện Cát Hải', city: '31' },
  { value: '318', label: 'Huyện Bạch Long Vĩ', city: '31' },
  { value: '323', label: 'Thành phố Hưng Yên', city: '33' },
  { value: '325', label: 'Huyện Văn Lâm', city: '33' },
  { value: '326', label: 'Huyện Văn Giang', city: '33' },
  { value: '327', label: 'Huyện Yên Mỹ', city: '33' },
  { value: '328', label: 'Huyện Mỹ Hào', city: '33' },
  { value: '329', label: 'Huyện Ân Thi', city: '33' },
  { value: '330', label: 'Huyện Khoái Châu', city: '33' },
  { value: '331', label: 'Huyện Kim Động', city: '33' },
  { value: '332', label: 'Huyện Tiên Lữ', city: '33' },
  { value: '333', label: 'Huyện Phù Cừ', city: '33' },
  { value: '336', label: 'Thành phố Thái Bình', city: '34' },
  { value: '338', label: 'Huyện Quỳnh Phụ', city: '34' },
  { value: '339', label: 'Huyện Hưng Hà', city: '34' },
  { value: '340', label: 'Huyện Đông Hưng', city: '34' },
  { value: '341', label: 'Huyện Thái Thụy', city: '34' },
  { value: '342', label: 'Huyện Tiền Hải', city: '34' },
  { value: '343', label: 'Huyện Kiến Xương', city: '34' },
  { value: '344', label: 'Huyện Vũ Thư', city: '34' },
  { value: '347', label: 'Thành phố Phủ Lý', city: '35' },
  { value: '349', label: 'Huyện Duy Tiên', city: '35' },
  { value: '350', label: 'Huyện Kim Bảng', city: '35' },
  { value: '351', label: 'Huyện Thanh Liêm', city: '35' },
  { value: '352', label: 'Huyện Bình Lục', city: '35' },
  { value: '353', label: 'Huyện Lý Nhân', city: '35' },
  { value: '356', label: 'Thành phố Nam Định', city: '36' },
  { value: '358', label: 'Huyện Mỹ Lộc', city: '36' },
  { value: '359', label: 'Huyện Vụ Bản', city: '36' },
  { value: '360', label: 'Huyện Ý Yên', city: '36' },
  { value: '361', label: 'Huyện Nghĩa Hưng', city: '36' },
  { value: '362', label: 'Huyện Nam Trực', city: '36' },
  { value: '363', label: 'Huyện Trực Ninh', city: '36' },
  { value: '364', label: 'Huyện Xuân Trường', city: '36' },
  { value: '365', label: 'Huyện Giao Thủy', city: '36' },
  { value: '366', label: 'Huyện Hải Hậu', city: '36' },
  { value: '369', label: 'Thành phố Ninh Bình', city: '37' },
  { value: '370', label: 'Thành phố Tam Điệp', city: '37' },
  { value: '372', label: 'Huyện Nho Quan', city: '37' },
  { value: '373', label: 'Huyện Gia Viễn', city: '37' },
  { value: '374', label: 'Huyện Hoa Lư', city: '37' },
  { value: '375', label: 'Huyện Yên Khánh', city: '37' },
  { value: '376', label: 'Huyện Kim Sơn', city: '37' },
  { value: '377', label: 'Huyện Yên Mô', city: '37' },
  { value: '380', label: 'Thành phố Thanh Hóa', city: '38' },
  { value: '381', label: 'Thị xã Bỉm Sơn', city: '38' },
  { value: '382', label: 'Thị xã Sầm Sơn', city: '38' },
  { value: '384', label: 'Huyện Mường Lát', city: '38' },
  { value: '385', label: 'Huyện Quan Hóa', city: '38' },
  { value: '386', label: 'Huyện Bá Thước', city: '38' },
  { value: '387', label: 'Huyện Quan Sơn', city: '38' },
  { value: '388', label: 'Huyện Lang Chánh', city: '38' },
  { value: '389', label: 'Huyện Ngọc Lặc', city: '38' },
  { value: '390', label: 'Huyện Cẩm Thủy', city: '38' },
  { value: '391', label: 'Huyện Thạch Thành', city: '38' },
  { value: '392', label: 'Huyện Hà Trung', city: '38' },
  { value: '393', label: 'Huyện Vĩnh Lộc', city: '38' },
  { value: '394', label: 'Huyện Yên Định', city: '38' },
  { value: '395', label: 'Huyện Thọ Xuân', city: '38' },
  { value: '396', label: 'Huyện Thường Xuân', city: '38' },
  { value: '397', label: 'Huyện Triệu Sơn', city: '38' },
  { value: '398', label: 'Huyện Thiệu Hóa', city: '38' },
  { value: '399', label: 'Huyện Hoằng Hóa', city: '38' },
  { value: '400', label: 'Huyện Hậu Lộc', city: '38' },
  { value: '401', label: 'Huyện Nga Sơn', city: '38' },
  { value: '402', label: 'Huyện Như Xuân', city: '38' },
  { value: '403', label: 'Huyện Như Thanh', city: '38' },
  { value: '404', label: 'Huyện Nông Cống', city: '38' },
  { value: '405', label: 'Huyện Đông Sơn', city: '38' },
  { value: '406', label: 'Huyện Quảng Xương', city: '38' },
  { value: '407', label: 'Huyện Tĩnh Gia', city: '38' },
  { value: '412', label: 'Thành phố Vinh', city: '40' },
  { value: '413', label: 'Thị xã Cửa Lò', city: '40' },
  { value: '414', label: 'Thị xã Thái Hoà', city: '40' },
  { value: '415', label: 'Huyện Quế Phong', city: '40' },
  { value: '416', label: 'Huyện Quỳ Châu', city: '40' },
  { value: '417', label: 'Huyện Kỳ Sơn', city: '40' },
  { value: '418', label: 'Huyện Tương Dương', city: '40' },
  { value: '419', label: 'Huyện Nghĩa Đàn', city: '40' },
  { value: '420', label: 'Huyện Quỳ Hợp', city: '40' },
  { value: '421', label: 'Huyện Quỳnh Lưu', city: '40' },
  { value: '422', label: 'Huyện Con Cuông', city: '40' },
  { value: '423', label: 'Huyện Tân Kỳ', city: '40' },
  { value: '424', label: 'Huyện Anh Sơn', city: '40' },
  { value: '425', label: 'Huyện Diễn Châu', city: '40' },
  { value: '426', label: 'Huyện Yên Thành', city: '40' },
  { value: '427', label: 'Huyện Đô Lương', city: '40' },
  { value: '428', label: 'Huyện Thanh Chương', city: '40' },
  { value: '429', label: 'Huyện Nghi Lộc', city: '40' },
  { value: '430', label: 'Huyện Nam Đàn', city: '40' },
  { value: '431', label: 'Huyện Hưng Nguyên', city: '40' },
  { value: '432', label: 'Thị xã Hoàng Mai', city: '40' },
  { value: '436', label: 'Thành phố Hà Tĩnh', city: '42' },
  { value: '437', label: 'Thị xã Hồng Lĩnh', city: '42' },
  { value: '439', label: 'Huyện Hương Sơn', city: '42' },
  { value: '440', label: 'Huyện Đức Thọ', city: '42' },
  { value: '441', label: 'Huyện Vũ Quang', city: '42' },
  { value: '442', label: 'Huyện Nghi Xuân', city: '42' },
  { value: '443', label: 'Huyện Can Lộc', city: '42' },
  { value: '444', label: 'Huyện Hương Khê', city: '42' },
  { value: '445', label: 'Huyện Thạch Hà', city: '42' },
  { value: '446', label: 'Huyện Cẩm Xuyên', city: '42' },
  { value: '447', label: 'Huyện Kỳ Anh', city: '42' },
  { value: '448', label: 'Huyện Lộc Hà', city: '42' },
  { value: '449', label: 'Thị xã Kỳ Anh', city: '42' },
  { value: '450', label: 'Thành Phố Đồng Hới', city: '44' },
  { value: '452', label: 'Huyện Minh Hóa', city: '44' },
  { value: '453', label: 'Huyện Tuyên Hóa', city: '44' },
  { value: '454', label: 'Huyện Quảng Trạch', city: '44' },
  { value: '455', label: 'Huyện Bố Trạch', city: '44' },
  { value: '456', label: 'Huyện Quảng Ninh', city: '44' },
  { value: '457', label: 'Huyện Lệ Thủy', city: '44' },
  { value: '458', label: 'Thị xã Ba Đồn', city: '44' },
  { value: '461', label: 'Thành phố Đông Hà', city: '45' },
  { value: '462', label: 'Thị xã Quảng Trị', city: '45' },
  { value: '464', label: 'Huyện Vĩnh Linh', city: '45' },
  { value: '465', label: 'Huyện Hướng Hóa', city: '45' },
  { value: '466', label: 'Huyện Gio Linh', city: '45' },
  { value: '467', label: 'Huyện Đa Krông', city: '45' },
  { value: '468', label: 'Huyện Cam Lộ', city: '45' },
  { value: '469', label: 'Huyện Triệu Phong', city: '45' },
  { value: '470', label: 'Huyện Hải Lăng', city: '45' },
  { value: '471', label: 'Huyện Cồn Cỏ', city: '45' },
  { value: '474', label: 'Thành phố Huế', city: '46' },
  { value: '476', label: 'Huyện Phong Điền', city: '46' },
  { value: '477', label: 'Huyện Quảng Điền', city: '46' },
  { value: '478', label: 'Huyện Phú Vang', city: '46' },
  { value: '479', label: 'Thị xã Hương Thủy', city: '46' },
  { value: '480', label: 'Thị xã Hương Trà', city: '46' },
  { value: '481', label: 'Huyện A Lưới', city: '46' },
  { value: '482', label: 'Huyện Phú Lộc', city: '46' },
  { value: '483', label: 'Huyện Nam Đông', city: '46' },
  { value: '490', label: 'Quận Liên Chiểu', city: '48' },
  { value: '491', label: 'Quận Thanh Khê', city: '48' },
  { value: '492', label: 'Quận Hải Châu', city: '48' },
  { value: '493', label: 'Quận Sơn Trà', city: '48' },
  { value: '494', label: 'Quận Ngũ Hành Sơn', city: '48' },
  { value: '495', label: 'Quận Cẩm Lệ', city: '48' },
  { value: '497', label: 'Huyện Hòa Vang', city: '48' },
  { value: '498', label: 'Huyện Hoàng Sa', city: '48' },
  { value: '502', label: 'Thành phố Tam Kỳ', city: '49' },
  { value: '503', label: 'Thành phố Hội An', city: '49' },
  { value: '504', label: 'Huyện Tây Giang', city: '49' },
  { value: '505', label: 'Huyện Đông Giang', city: '49' },
  { value: '506', label: 'Huyện Đại Lộc', city: '49' },
  { value: '507', label: 'Thị xã Điện Bàn', city: '49' },
  { value: '508', label: 'Huyện Duy Xuyên', city: '49' },
  { value: '509', label: 'Huyện Quế Sơn', city: '49' },
  { value: '510', label: 'Huyện Nam Giang', city: '49' },
  { value: '511', label: 'Huyện Phước Sơn', city: '49' },
  { value: '512', label: 'Huyện Hiệp Đức', city: '49' },
  { value: '513', label: 'Huyện Thăng Bình', city: '49' },
  { value: '514', label: 'Huyện Tiên Phước', city: '49' },
  { value: '515', label: 'Huyện Bắc Trà My', city: '49' },
  { value: '516', label: 'Huyện Nam Trà My', city: '49' },
  { value: '517', label: 'Huyện Núi Thành', city: '49' },
  { value: '518', label: 'Huyện Phú Ninh', city: '49' },
  { value: '519', label: 'Huyện Nông Sơn', city: '49' },
  { value: '522', label: 'Thành phố Quảng Ngãi', city: '51' },
  { value: '524', label: 'Huyện Bình Sơn', city: '51' },
  { value: '525', label: 'Huyện Trà Bồng', city: '51' },
  { value: '526', label: 'Huyện Tây Trà', city: '51' },
  { value: '527', label: 'Huyện Sơn Tịnh', city: '51' },
  { value: '528', label: 'Huyện Tư Nghĩa', city: '51' },
  { value: '529', label: 'Huyện Sơn Hà', city: '51' },
  { value: '530', label: 'Huyện Sơn Tây', city: '51' },
  { value: '531', label: 'Huyện Minh Long', city: '51' },
  { value: '532', label: 'Huyện Nghĩa Hành', city: '51' },
  { value: '533', label: 'Huyện Mộ Đức', city: '51' },
  { value: '534', label: 'Huyện Đức Phổ', city: '51' },
  { value: '535', label: 'Huyện Ba Tơ', city: '51' },
  { value: '536', label: 'Huyện Lý Sơn', city: '51' },
  { value: '540', label: 'Thành phố Qui Nhơn', city: '52' },
  { value: '542', label: 'Huyện An Lão', city: '52' },
  { value: '543', label: 'Huyện Hoài Nhơn', city: '52' },
  { value: '544', label: 'Huyện Hoài Ân', city: '52' },
  { value: '545', label: 'Huyện Phù Mỹ', city: '52' },
  { value: '546', label: 'Huyện Vĩnh Thạnh', city: '52' },
  { value: '547', label: 'Huyện Tây Sơn', city: '52' },
  { value: '548', label: 'Huyện Phù Cát', city: '52' },
  { value: '549', label: 'Thị xã An Nhơn', city: '52' },
  { value: '550', label: 'Huyện Tuy Phước', city: '52' },
  { value: '551', label: 'Huyện Vân Canh', city: '52' },
  { value: '555', label: 'Thành phố Tuy Hoà', city: '54' },
  { value: '557', label: 'Thị xã Sông Cầu', city: '54' },
  { value: '558', label: 'Huyện Đồng Xuân', city: '54' },
  { value: '559', label: 'Huyện Tuy An', city: '54' },
  { value: '560', label: 'Huyện Sơn Hòa', city: '54' },
  { value: '561', label: 'Huyện Sông Hinh', city: '54' },
  { value: '562', label: 'Huyện Tây Hoà', city: '54' },
  { value: '563', label: 'Huyện Phú Hoà', city: '54' },
  { value: '564', label: 'Huyện Đông Hòa', city: '54' },
  { value: '568', label: 'Thành phố Nha Trang', city: '56' },
  { value: '569', label: 'Thành phố Cam Ranh', city: '56' },
  { value: '570', label: 'Huyện Cam Lâm', city: '56' },
  { value: '571', label: 'Huyện Vạn Ninh', city: '56' },
  { value: '572', label: 'Thị xã Ninh Hòa', city: '56' },
  { value: '573', label: 'Huyện Khánh Vĩnh', city: '56' },
  { value: '574', label: 'Huyện Diên Khánh', city: '56' },
  { value: '575', label: 'Huyện Khánh Sơn', city: '56' },
  { value: '576', label: 'Huyện Trường Sa', city: '56' },
  { value: '582', label: 'Thành phố Phan Rang-Tháp Chàm', city: '58' },
  { value: '584', label: 'Huyện Bác Ái', city: '58' },
  { value: '585', label: 'Huyện Ninh Sơn', city: '58' },
  { value: '586', label: 'Huyện Ninh Hải', city: '58' },
  { value: '587', label: 'Huyện Ninh Phước', city: '58' },
  { value: '588', label: 'Huyện Thuận Bắc', city: '58' },
  { value: '589', label: 'Huyện Thuận Nam', city: '58' },
  { value: '593', label: 'Thành phố Phan Thiết', city: '60' },
  { value: '594', label: 'Thị xã La Gi', city: '60' },
  { value: '595', label: 'Huyện Tuy Phong', city: '60' },
  { value: '596', label: 'Huyện Bắc Bình', city: '60' },
  { value: '597', label: 'Huyện Hàm Thuận Bắc', city: '60' },
  { value: '598', label: 'Huyện Hàm Thuận Nam', city: '60' },
  { value: '599', label: 'Huyện Tánh Linh', city: '60' },
  { value: '600', label: 'Huyện Đức Linh', city: '60' },
  { value: '601', label: 'Huyện Hàm Tân', city: '60' },
  { value: '602', label: 'Huyện Phú Quí', city: '60' },
  { value: '608', label: 'Thành phố Kon Tum', city: '62' },
  { value: '610', label: 'Huyện Đắk Glei', city: '62' },
  { value: '611', label: 'Huyện Ngọc Hồi', city: '62' },
  { value: '612', label: 'Huyện Đắk Tô', city: '62' },
  { value: '613', label: 'Huyện Kon Plông', city: '62' },
  { value: '614', label: 'Huyện Kon Rẫy', city: '62' },
  { value: '615', label: 'Huyện Đắk Hà', city: '62' },
  { value: '616', label: 'Huyện Sa Thầy', city: '62' },
  { value: '617', label: 'Huyện Tu Mơ Rông', city: '62' },
  { value: '618', label: 'Huyện Ia H\' Drai', city: '62' },
  { value: '622', label: 'Thành phố Pleiku', city: '64' },
  { value: '623', label: 'Thị xã An Khê', city: '64' },
  { value: '624', label: 'Thị xã Ayun Pa', city: '64' },
  { value: '625', label: 'Huyện KBang', city: '64' },
  { value: '626', label: 'Huyện Đăk Đoa', city: '64' },
  { value: '627', label: 'Huyện Chư Păh', city: '64' },
  { value: '628', label: 'Huyện Ia Grai', city: '64' },
  { value: '629', label: 'Huyện Mang Yang', city: '64' },
  { value: '630', label: 'Huyện Kông Chro', city: '64' },
  { value: '631', label: 'Huyện Đức Cơ', city: '64' },
  { value: '632', label: 'Huyện Chư Prông', city: '64' },
  { value: '633', label: 'Huyện Chư Sê', city: '64' },
  { value: '634', label: 'Huyện Đăk Pơ', city: '64' },
  { value: '635', label: 'Huyện Ia Pa', city: '64' },
  { value: '637', label: 'Huyện Krông Pa', city: '64' },
  { value: '638', label: 'Huyện Phú Thiện', city: '64' },
  { value: '639', label: 'Huyện Chư Pưh', city: '64' },
  { value: '643', label: 'Thành phố Buôn Ma Thuột', city: '66' },
  { value: '644', label: 'Thị Xã Buôn Hồ', city: '66' },
  { value: '645', label: 'Huyện Ea H\'leo', city: '66' },
  { value: '646', label: 'Huyện Ea Súp', city: '66' },
  { value: '647', label: 'Huyện Buôn Đôn', city: '66' },
  { value: '648', label: 'Huyện Cư M\'gar', city: '66' },
  { value: '649', label: 'Huyện Krông Búk', city: '66' },
  { value: '650', label: 'Huyện Krông Năng', city: '66' },
  { value: '651', label: 'Huyện Ea Kar', city: '66' },
  { value: '652', label: 'Huyện M\'Đrắk', city: '66' },
  { value: '653', label: 'Huyện Krông Bông', city: '66' },
  { value: '654', label: 'Huyện Krông Pắc', city: '66' },
  { value: '655', label: 'Huyện Krông A Na', city: '66' },
  { value: '656', label: 'Huyện Lắk', city: '66' },
  { value: '657', label: 'Huyện Cư Kuin', city: '66' },
  { value: '660', label: 'Thị xã Gia Nghĩa', city: '67' },
  { value: '661', label: 'Huyện Đăk Glong', city: '67' },
  { value: '662', label: 'Huyện Cư Jút', city: '67' },
  { value: '663', label: 'Huyện Đắk Mil', city: '67' },
  { value: '664', label: 'Huyện Krông Nô', city: '67' },
  { value: '665', label: 'Huyện Đắk Song', city: '67' },
  { value: '666', label: 'Huyện Đắk R\'Lấp', city: '67' },
  { value: '667', label: 'Huyện Tuy Đức', city: '67' },
  { value: '672', label: 'Thành phố Đà Lạt', city: '68' },
  { value: '673', label: 'Thành phố Bảo Lộc', city: '68' },
  { value: '674', label: 'Huyện Đam Rông', city: '68' },
  { value: '675', label: 'Huyện Lạc Dương', city: '68' },
  { value: '676', label: 'Huyện Lâm Hà', city: '68' },
  { value: '677', label: 'Huyện Đơn Dương', city: '68' },
  { value: '678', label: 'Huyện Đức Trọng', city: '68' },
  { value: '679', label: 'Huyện Di Linh', city: '68' },
  { value: '680', label: 'Huyện Bảo Lâm', city: '68' },
  { value: '681', label: 'Huyện Đạ Huoai', city: '68' },
  { value: '682', label: 'Huyện Đạ Tẻh', city: '68' },
  { value: '683', label: 'Huyện Cát Tiên', city: '68' },
  { value: '688', label: 'Thị xã Phước Long', city: '70' },
  { value: '689', label: 'Thị xã Đồng Xoài', city: '70' },
  { value: '690', label: 'Thị xã Bình Long', city: '70' },
  { value: '691', label: 'Huyện Bù Gia Mập', city: '70' },
  { value: '692', label: 'Huyện Lộc Ninh', city: '70' },
  { value: '693', label: 'Huyện Bù Đốp', city: '70' },
  { value: '694', label: 'Huyện Hớn Quản', city: '70' },
  { value: '695', label: 'Huyện Đồng Phú', city: '70' },
  { value: '696', label: 'Huyện Bù Đăng', city: '70' },
  { value: '697', label: 'Huyện Chơn Thành', city: '70' },
  { value: '698', label: 'Huyện Phú Riềng', city: '70' },
  { value: '703', label: 'Thành phố Tây Ninh', city: '72' },
  { value: '705', label: 'Huyện Tân Biên', city: '72' },
  { value: '706', label: 'Huyện Tân Châu', city: '72' },
  { value: '707', label: 'Huyện Dương Minh Châu', city: '72' },
  { value: '708', label: 'Huyện Châu Thành', city: '72' },
  { value: '709', label: 'Huyện Hòa Thành', city: '72' },
  { value: '710', label: 'Huyện Gò Dầu', city: '72' },
  { value: '711', label: 'Huyện Bến Cầu', city: '72' },
  { value: '712', label: 'Huyện Trảng Bàng', city: '72' },
  { value: '718', label: 'Thành phố Thủ Dầu Một', city: '74' },
  { value: '719', label: 'Huyện Bàu Bàng', city: '74' },
  { value: '720', label: 'Huyện Dầu Tiếng', city: '74' },
  { value: '721', label: 'Thị xã Bến Cát', city: '74' },
  { value: '722', label: 'Huyện Phú Giáo', city: '74' },
  { value: '723', label: 'Thị xã Tân Uyên', city: '74' },
  { value: '724', label: 'Thị xã Dĩ An', city: '74' },
  { value: '725', label: 'Thị xã Thuận An', city: '74' },
  { value: '726', label: 'Huyện Bắc Tân Uyên', city: '74' },
  { value: '731', label: 'Thành phố Biên Hòa', city: '75' },
  { value: '732', label: 'Thị xã Long Khánh', city: '75' },
  { value: '734', label: 'Huyện Tân Phú', city: '75' },
  { value: '735', label: 'Huyện Vĩnh Cửu', city: '75' },
  { value: '736', label: 'Huyện Định Quán', city: '75' },
  { value: '737', label: 'Huyện Trảng Bom', city: '75' },
  { value: '738', label: 'Huyện Thống Nhất', city: '75' },
  { value: '739', label: 'Huyện Cẩm Mỹ', city: '75' },
  { value: '740', label: 'Huyện Long Thành', city: '75' },
  { value: '741', label: 'Huyện Xuân Lộc', city: '75' },
  { value: '742', label: 'Huyện Nhơn Trạch', city: '75' },
  { value: '747', label: 'Thành phố Vũng Tàu', city: '77' },
  { value: '748', label: 'Thành phố Bà Rịa', city: '77' },
  { value: '750', label: 'Huyện Châu Đức', city: '77' },
  { value: '751', label: 'Huyện Xuyên Mộc', city: '77' },
  { value: '752', label: 'Huyện Long Điền', city: '77' },
  { value: '753', label: 'Huyện Đất Đỏ', city: '77' },
  { value: '754', label: 'Huyện Tân Thành', city: '77' },
  { value: '755', label: 'Huyện Côn Đảo', city: '77' },
  { value: '760', label: 'Quận 1', city: '79' },
  { value: '761', label: 'Quận 12', city: '79' },
  { value: '762', label: 'Quận Thủ Đức', city: '79' },
  { value: '763', label: 'Quận 9', city: '79' },
  { value: '764', label: 'Quận Gò Vấp', city: '79' },
  { value: '765', label: 'Quận Bình Thạnh', city: '79' },
  { value: '766', label: 'Quận Tân Bình', city: '79' },
  { value: '767', label: 'Quận Tân Phú', city: '79' },
  { value: '768', label: 'Quận Phú Nhuận', city: '79' },
  { value: '769', label: 'Quận 2', city: '79' },
  { value: '770', label: 'Quận 3', city: '79' },
  { value: '771', label: 'Quận 10', city: '79' },
  { value: '772', label: 'Quận 11', city: '79' },
  { value: '773', label: 'Quận 4', city: '79' },
  { value: '774', label: 'Quận 5', city: '79' },
  { value: '775', label: 'Quận 6', city: '79' },
  { value: '776', label: 'Quận 8', city: '79' },
  { value: '777', label: 'Quận Bình Tân', city: '79' },
  { value: '778', label: 'Quận 7', city: '79' },
  { value: '783', label: 'Huyện Củ Chi', city: '79' },
  { value: '784', label: 'Huyện Hóc Môn', city: '79' },
  { value: '785', label: 'Huyện Bình Chánh', city: '79' },
  { value: '786', label: 'Huyện Nhà Bè', city: '79' },
  { value: '787', label: 'Huyện Cần Giờ', city: '79' },
  { value: '794', label: 'Thành phố Tân An', city: '80' },
  { value: '795', label: 'Thị xã Kiến Tường', city: '80' },
  { value: '796', label: 'Huyện Tân Hưng', city: '80' },
  { value: '797', label: 'Huyện Vĩnh Hưng', city: '80' },
  { value: '798', label: 'Huyện Mộc Hóa', city: '80' },
  { value: '799', label: 'Huyện Tân Thạnh', city: '80' },
  { value: '800', label: 'Huyện Thạnh Hóa', city: '80' },
  { value: '801', label: 'Huyện Đức Huệ', city: '80' },
  { value: '802', label: 'Huyện Đức Hòa', city: '80' },
  { value: '803', label: 'Huyện Bến Lức', city: '80' },
  { value: '804', label: 'Huyện Thủ Thừa', city: '80' },
  { value: '805', label: 'Huyện Tân Trụ', city: '80' },
  { value: '806', label: 'Huyện Cần Đước', city: '80' },
  { value: '807', label: 'Huyện Cần Giuộc', city: '80' },
  { value: '808', label: 'Huyện Châu Thành', city: '80' },
  { value: '815', label: 'Thành phố Mỹ Tho', city: '82' },
  { value: '816', label: 'Thị xã Gò Công', city: '82' },
  { value: '817', label: 'Thị xã Cai Lậy', city: '82' },
  { value: '818', label: 'Huyện Tân Phước', city: '82' },
  { value: '819', label: 'Huyện Cái Bè', city: '82' },
  { value: '820', label: 'Huyện Cai Lậy', city: '82' },
  { value: '821', label: 'Huyện Châu Thành', city: '82' },
  { value: '822', label: 'Huyện Chợ Gạo', city: '82' },
  { value: '823', label: 'Huyện Gò Công Tây', city: '82' },
  { value: '824', label: 'Huyện Gò Công Đông', city: '82' },
  { value: '825', label: 'Huyện Tân Phú Đông', city: '82' },
  { value: '829', label: 'Thành phố Bến Tre', city: '83' },
  { value: '831', label: 'Huyện Châu Thành', city: '83' },
  { value: '832', label: 'Huyện Chợ Lách', city: '83' },
  { value: '833', label: 'Huyện Mỏ Cày Nam', city: '83' },
  { value: '834', label: 'Huyện Giồng Trôm', city: '83' },
  { value: '835', label: 'Huyện Bình Đại', city: '83' },
  { value: '836', label: 'Huyện Ba Tri', city: '83' },
  { value: '837', label: 'Huyện Thạnh Phú', city: '83' },
  { value: '838', label: 'Huyện Mỏ Cày Bắc', city: '83' },
  { value: '842', label: 'Thành phố Trà Vinh', city: '84' },
  { value: '844', label: 'Huyện Càng Long', city: '84' },
  { value: '845', label: 'Huyện Cầu Kè', city: '84' },
  { value: '846', label: 'Huyện Tiểu Cần', city: '84' },
  { value: '847', label: 'Huyện Châu Thành', city: '84' },
  { value: '848', label: 'Huyện Cầu Ngang', city: '84' },
  { value: '849', label: 'Huyện Trà Cú', city: '84' },
  { value: '850', label: 'Huyện Duyên Hải', city: '84' },
  { value: '851', label: 'Thị xã Duyên Hải', city: '84' },
  { value: '855', label: 'Thành phố Vĩnh Long', city: '86' },
  { value: '857', label: 'Huyện Long Hồ', city: '86' },
  { value: '858', label: 'Huyện Mang Thít', city: '86' },
  { value: '859', label: 'Huyện  Vũng Liêm', city: '86' },
  { value: '860', label: 'Huyện Tam Bình', city: '86' },
  { value: '861', label: 'Thị xã Bình Minh', city: '86' },
  { value: '862', label: 'Huyện Trà Ôn', city: '86' },
  { value: '863', label: 'Huyện Bình Tân', city: '86' },
  { value: '866', label: 'Thành phố Cao Lãnh', city: '87' },
  { value: '867', label: 'Thành phố Sa Đéc', city: '87' },
  { value: '868', label: 'Thị xã Hồng Ngự', city: '87' },
  { value: '869', label: 'Huyện Tân Hồng', city: '87' },
  { value: '870', label: 'Huyện Hồng Ngự', city: '87' },
  { value: '871', label: 'Huyện Tam Nông', city: '87' },
  { value: '872', label: 'Huyện Tháp Mười', city: '87' },
  { value: '873', label: 'Huyện Cao Lãnh', city: '87' },
  { value: '874', label: 'Huyện Thanh Bình', city: '87' },
  { value: '875', label: 'Huyện Lấp Vò', city: '87' },
  { value: '876', label: 'Huyện Lai Vung', city: '87' },
  { value: '877', label: 'Huyện Châu Thành', city: '87' },
  { value: '883', label: 'Thành phố Long Xuyên', city: '89' },
  { value: '884', label: 'Thành phố Châu Đốc', city: '89' },
  { value: '886', label: 'Huyện An Phú', city: '89' },
  { value: '887', label: 'Thị xã Tân Châu', city: '89' },
  { value: '888', label: 'Huyện Phú Tân', city: '89' },
  { value: '889', label: 'Huyện Châu Phú', city: '89' },
  { value: '890', label: 'Huyện Tịnh Biên', city: '89' },
  { value: '891', label: 'Huyện Tri Tôn', city: '89' },
  { value: '892', label: 'Huyện Châu Thành', city: '89' },
  { value: '893', label: 'Huyện Chợ Mới', city: '89' },
  { value: '894', label: 'Huyện Thoại Sơn', city: '89' },
  { value: '899', label: 'Thành phố Rạch Giá', city: '91' },
  { value: '900', label: 'Thị xã Hà Tiên', city: '91' },
  { value: '902', label: 'Huyện Kiên Lương', city: '91' },
  { value: '903', label: 'Huyện Hòn Đất', city: '91' },
  { value: '904', label: 'Huyện Tân Hiệp', city: '91' },
  { value: '905', label: 'Huyện Châu Thành', city: '91' },
  { value: '906', label: 'Huyện Giồng Riềng', city: '91' },
  { value: '907', label: 'Huyện Gò Quao', city: '91' },
  { value: '908', label: 'Huyện An Biên', city: '91' },
  { value: '909', label: 'Huyện An Minh', city: '91' },
  { value: '910', label: 'Huyện Vĩnh Thuận', city: '91' },
  { value: '911', label: 'Huyện Phú Quốc', city: '91' },
  { value: '912', label: 'Huyện Kiên Hải', city: '91' },
  { value: '913', label: 'Huyện U Minh Thượng', city: '91' },
  { value: '914', label: 'Huyện Giang Thành', city: '91' },
  { value: '916', label: 'Quận Ninh Kiều', city: '92' },
  { value: '917', label: 'Quận Ô Môn', city: '92' },
  { value: '918', label: 'Quận Bình Thuỷ', city: '92' },
  { value: '919', label: 'Quận Cái Răng', city: '92' },
  { value: '923', label: 'Quận Thốt Nốt', city: '92' },
  { value: '924', label: 'Huyện Vĩnh Thạnh', city: '92' },
  { value: '925', label: 'Huyện Cờ Đỏ', city: '92' },
  { value: '926', label: 'Huyện Phong Điền', city: '92' },
  { value: '927', label: 'Huyện Thới Lai', city: '92' },
  { value: '930', label: 'Thành phố Vị Thanh', city: '93' },
  { value: '931', label: 'Thị xã Ngã Bảy', city: '93' },
  { value: '932', label: 'Huyện Châu Thành A', city: '93' },
  { value: '933', label: 'Huyện Châu Thành', city: '93' },
  { value: '934', label: 'Huyện Phụng Hiệp', city: '93' },
  { value: '935', label: 'Huyện Vị Thuỷ', city: '93' },
  { value: '936', label: 'Huyện Long Mỹ', city: '93' },
  { value: '937', label: 'Thị xã Long Mỹ', city: '93' },
  { value: '941', label: 'Thành phố Sóc Trăng', city: '94' },
  { value: '942', label: 'Huyện Châu Thành', city: '94' },
  { value: '943', label: 'Huyện Kế Sách', city: '94' },
  { value: '944', label: 'Huyện Mỹ Tú', city: '94' },
  { value: '945', label: 'Huyện Cù Lao Dung', city: '94' },
  { value: '946', label: 'Huyện Long Phú', city: '94' },
  { value: '947', label: 'Huyện Mỹ Xuyên', city: '94' },
  { value: '948', label: 'Thị xã Ngã Năm', city: '94' },
  { value: '949', label: 'Huyện Thạnh Trị', city: '94' },
  { value: '950', label: 'Thị xã Vĩnh Châu', city: '94' },
  { value: '951', label: 'Huyện Trần Đề', city: '94' },
  { value: '954', label: 'Thành phố Bạc Liêu', city: '95' },
  { value: '956', label: 'Huyện Hồng Dân', city: '95' },
  { value: '957', label: 'Huyện Phước Long', city: '95' },
  { value: '958', label: 'Huyện Vĩnh Lợi', city: '95' },
  { value: '959', label: 'Thị xã Giá Rai', city: '95' },
  { value: '960', label: 'Huyện Đông Hải', city: '95' },
  { value: '961', label: 'Huyện Hoà Bình', city: '95' },
  { value: '964', label: 'Thành phố Cà Mau', city: '96' },
  { value: '966', label: 'Huyện U Minh', city: '96' },
  { value: '967', label: 'Huyện Thới Bình', city: '96' },
  { value: '968', label: 'Huyện Trần Văn Thời', city: '96' },
  { value: '969', label: 'Huyện Cái Nước', city: '96' },
  { value: '970', label: 'Huyện Đầm Dơi', city: '96' },
  { value: '971', label: 'Huyện Năm Căn', city: '96' },
  { value: '972', label: 'Huyện Phú Tân', city: '96' },
  { value: '973', label: 'Huyện Ngọc Hiển', city: '96' }
]
